// Copyright Valkey GLIDE Project Contributors - SPDX Identifier: Apache-2.0
// Manual protobuf serialization matching connection_request.proto field numbers.
// In production, this would be auto-generated by protoc. This manual implementation
// ensures wire-format compatibility with the Rust core's protobuf deserialization.

using Google.Protobuf;

namespace Glide.Protobuf;

/// <summary>
/// Represents a ConnectionRequest protobuf message.
/// Serializes to wire format compatible with glide-core/src/protobuf/connection_request.proto.
/// </summary>
public class ConnectionRequest
{
    // Field numbers from connection_request.proto
    private const int AddressesFieldNumber = 1;
    private const int TlsModeFieldNumber = 2;
    private const int ClusterModeEnabledFieldNumber = 3;
    private const int RequestTimeoutFieldNumber = 4;
    private const int ReadFromFieldNumber = 5;
    private const int ConnectionRetryStrategyFieldNumber = 6;
    private const int AuthenticationInfoFieldNumber = 7;
    private const int DatabaseIdFieldNumber = 8;
    private const int ProtocolFieldNumber = 9;
    private const int ClientNameFieldNumber = 10;
    private const int InflightRequestsLimitFieldNumber = 14;
    private const int ClientAzFieldNumber = 15;
    private const int LazyConnectFieldNumber = 17;
    private const int CompressionConfigFieldNumber = 21;

    public List<NodeAddress> Addresses { get; } = new();
    public TlsMode TlsMode { get; set; }
    public bool ClusterModeEnabled { get; set; }
    public uint RequestTimeout { get; set; }
    public ReadFrom ReadFrom { get; set; }
    public ConnectionRetryStrategy? ConnectionRetryStrategy { get; set; }
    public AuthenticationInfo? AuthenticationInfo { get; set; }
    public uint DatabaseId { get; set; }
    public ProtocolVersion Protocol { get; set; }
    public string? ClientName { get; set; }
    public uint InflightRequestsLimit { get; set; }
    public string? ClientAz { get; set; }
    public bool LazyConnect { get; set; }
    public CompressionConfig? CompressionConfig { get; set; }

    /// <summary>
    /// Serializes this ConnectionRequest to protobuf wire format bytes.
    /// </summary>
    public byte[] ToByteArray()
    {
        using var stream = new MemoryStream();
        var output = new CodedOutputStream(stream);

        // Field 1: repeated NodeAddress addresses (embedded message)
        foreach (var addr in Addresses)
        {
            WriteNodeAddress(output, addr);
        }

        // Field 2: TlsMode tls_mode (enum)
        if (TlsMode != TlsMode.NoTls)
            output.WriteTag(TlsModeFieldNumber, WireFormat.WireType.Varint);
        if (TlsMode != TlsMode.NoTls)
            output.WriteEnum((int)TlsMode);

        // Field 3: bool cluster_mode_enabled
        if (ClusterModeEnabled)
        {
            output.WriteTag(ClusterModeEnabledFieldNumber, WireFormat.WireType.Varint);
            output.WriteBool(true);
        }

        // Field 4: uint32 request_timeout
        if (RequestTimeout > 0)
        {
            output.WriteTag(RequestTimeoutFieldNumber, WireFormat.WireType.Varint);
            output.WriteUInt32(RequestTimeout);
        }

        // Field 5: ReadFrom read_from (enum)
        if (ReadFrom != ReadFrom.Primary)
        {
            output.WriteTag(ReadFromFieldNumber, WireFormat.WireType.Varint);
            output.WriteEnum((int)ReadFrom);
        }

        // Field 6: ConnectionRetryStrategy (embedded message)
        if (ConnectionRetryStrategy != null)
        {
            WriteRetryStrategy(output, ConnectionRetryStrategy);
        }

        // Field 7: AuthenticationInfo (embedded message)
        if (AuthenticationInfo != null)
        {
            WriteAuthInfo(output, AuthenticationInfo);
        }

        // Field 8: uint32 database_id
        if (DatabaseId > 0)
        {
            output.WriteTag(DatabaseIdFieldNumber, WireFormat.WireType.Varint);
            output.WriteUInt32(DatabaseId);
        }

        // Field 9: ProtocolVersion protocol (enum)
        if (Protocol != ProtocolVersion.Resp3)
        {
            output.WriteTag(ProtocolFieldNumber, WireFormat.WireType.Varint);
            output.WriteEnum((int)Protocol);
        }

        // Field 10: string client_name
        if (!string.IsNullOrEmpty(ClientName))
        {
            output.WriteTag(ClientNameFieldNumber, WireFormat.WireType.LengthDelimited);
            output.WriteString(ClientName);
        }

        // Field 14: uint32 inflight_requests_limit
        if (InflightRequestsLimit > 0)
        {
            output.WriteTag(InflightRequestsLimitFieldNumber, WireFormat.WireType.Varint);
            output.WriteUInt32(InflightRequestsLimit);
        }

        // Field 15: string client_az
        if (!string.IsNullOrEmpty(ClientAz))
        {
            output.WriteTag(ClientAzFieldNumber, WireFormat.WireType.LengthDelimited);
            output.WriteString(ClientAz);
        }

        // Field 17: bool lazy_connect
        if (LazyConnect)
        {
            output.WriteTag(LazyConnectFieldNumber, WireFormat.WireType.Varint);
            output.WriteBool(true);
        }

        // Field 21: optional CompressionConfig compression_config (embedded message)
        if (CompressionConfig != null)
        {
            WriteCompressionConfig(output, CompressionConfig);
        }

        output.Flush();
        return stream.ToArray();
    }

    private static void WriteNodeAddress(CodedOutputStream output, NodeAddress addr)
    {
        // Calculate size of inner message
        using var innerStream = new MemoryStream();
        var innerOutput = new CodedOutputStream(innerStream);

        if (!string.IsNullOrEmpty(addr.Host))
        {
            innerOutput.WriteTag(1, WireFormat.WireType.LengthDelimited);
            innerOutput.WriteString(addr.Host);
        }
        if (addr.Port > 0)
        {
            innerOutput.WriteTag(2, WireFormat.WireType.Varint);
            innerOutput.WriteUInt32(addr.Port);
        }
        innerOutput.Flush();

        output.WriteTag(AddressesFieldNumber, WireFormat.WireType.LengthDelimited);
        output.WriteBytes(ByteString.CopyFrom(innerStream.ToArray()));
    }

    private static void WriteRetryStrategy(CodedOutputStream output, ConnectionRetryStrategy strategy)
    {
        using var innerStream = new MemoryStream();
        var innerOutput = new CodedOutputStream(innerStream);

        if (strategy.NumberOfRetries > 0)
        {
            innerOutput.WriteTag(1, WireFormat.WireType.Varint);
            innerOutput.WriteUInt32(strategy.NumberOfRetries);
        }
        if (strategy.Factor > 0)
        {
            innerOutput.WriteTag(2, WireFormat.WireType.Varint);
            innerOutput.WriteUInt32(strategy.Factor);
        }
        if (strategy.ExponentBase > 0)
        {
            innerOutput.WriteTag(3, WireFormat.WireType.Varint);
            innerOutput.WriteUInt32(strategy.ExponentBase);
        }
        if (strategy.JitterPercent.HasValue)
        {
            innerOutput.WriteTag(4, WireFormat.WireType.Varint);
            innerOutput.WriteUInt32(strategy.JitterPercent.Value);
        }
        innerOutput.Flush();

        output.WriteTag(ConnectionRetryStrategyFieldNumber, WireFormat.WireType.LengthDelimited);
        output.WriteBytes(ByteString.CopyFrom(innerStream.ToArray()));
    }

    private static void WriteAuthInfo(CodedOutputStream output, AuthenticationInfo auth)
    {
        using var innerStream = new MemoryStream();
        var innerOutput = new CodedOutputStream(innerStream);

        if (!string.IsNullOrEmpty(auth.Password))
        {
            innerOutput.WriteTag(1, WireFormat.WireType.LengthDelimited);
            innerOutput.WriteString(auth.Password);
        }
        if (!string.IsNullOrEmpty(auth.Username))
        {
            innerOutput.WriteTag(2, WireFormat.WireType.LengthDelimited);
            innerOutput.WriteString(auth.Username);
        }
        innerOutput.Flush();

        output.WriteTag(AuthenticationInfoFieldNumber, WireFormat.WireType.LengthDelimited);
        output.WriteBytes(ByteString.CopyFrom(innerStream.ToArray()));
    }

    private static void WriteCompressionConfig(CodedOutputStream output, CompressionConfig config)
    {
        using var innerStream = new MemoryStream();
        var innerOutput = new CodedOutputStream(innerStream);

        // Field 1: bool enabled
        if (config.Enabled)
        {
            innerOutput.WriteTag(1, WireFormat.WireType.Varint);
            innerOutput.WriteBool(true);
        }

        // Field 2: CompressionBackend backend (enum)
        if (config.Backend != CompressionBackend.Zstd)
        {
            innerOutput.WriteTag(2, WireFormat.WireType.Varint);
            innerOutput.WriteEnum((int)config.Backend);
        }

        // Field 3: optional int32 compression_level
        if (config.CompressionLevel.HasValue)
        {
            innerOutput.WriteTag(3, WireFormat.WireType.Varint);
            innerOutput.WriteInt32(config.CompressionLevel.Value);
        }

        // Field 4: uint32 min_compression_size
        if (config.MinCompressionSize > 0)
        {
            innerOutput.WriteTag(4, WireFormat.WireType.Varint);
            innerOutput.WriteUInt32(config.MinCompressionSize);
        }

        innerOutput.Flush();

        output.WriteTag(CompressionConfigFieldNumber, WireFormat.WireType.LengthDelimited);
        output.WriteBytes(ByteString.CopyFrom(innerStream.ToArray()));
    }
}
